CREATE TABLE REGISTROVENTAS
(
  DUAL bigint NOT NULL,
  FECHAEMISION date,
  FECHAVENCIMIENTO date,
  TIPOCOMPROBANTE smallint,
  SERIECO varchar(8),
  NUMEROCO integer,
  TIPODOCUMENTO varchar(2),
  NRODOCUMENTO varchar(12),
  RAZONNOMBRE varchar(128),
  DIRECCION varchar(250),
  VEXPORTACION numeric(16,6),
  IGVTASA numeric(12,6),
  IGVIPM numeric(16,6),
  ISC numeric(16,6),
  OTROSTRIBUTOS numeric(16,6),
  BASEIMPONIBLE numeric(16,6),
  INAFECTAS numeric(16,6),
  TOTALEXONERADA numeric(16,6),
  GRATUITAS numeric(16,6),
  TIPODSCTO smallint,
  DSCTOUNIT numeric(12,6),
  DSCTOGLOBAL numeric(12,2),
  DESCUENTOS numeric(16,6),
  TIPOCARGO smallint,
  CARGOUNIT numeric(12,6),
  CARGOGLOBAL numeric(12,2),
  CARGOS numeric(16,6),
  IMPORTETOTAL numeric(16,6),
  MONEDA varchar(4) DEFAULT 'PEN',
  TIPOCAMBIO numeric(16,6),
  PERCEPUNIT numeric(12,6),
  PERCEPCION numeric(16,6),
  TIPOPAGO smallint,
  RCPFECHA date,
  RCPTIPO varchar(2),
  RCPSERIE varchar(8),
  RCPNUMERO varchar(16),
  MOTIVONOTA varchar(64),
  CODIGONOTA varchar(3),
  TIPOGUIA smallint DEFAULT 9,
  GUIAREMISION varchar(128),
  PLACA varchar(12),
  FECHATURNO date,
  TURNO smallint,
  HORA time,
  PUNTOVENTA smallint,
  MAQUINAVENTA smallint,
  SITUACION smallint,
  ENVIOSUNAT smallint DEFAULT 0,
  FECHAENVIO date,
  IDSESION integer,
  CAJERO varchar(64),
  AFECTARSTOCK smallint DEFAULT 1,
  NPFACTURADO smallint DEFAULT 0,
  ENVIOCONTABILIDAD bigint DEFAULT 0,
  USERID varchar(32),
  GLOSA varchar(128),
  TRANSPORTABLE smallint DEFAULT 0,
  ENVIOWEB smallint DEFAULT 0,
  RESOLUCION smallint DEFAULT 0,
  ALMACEN varchar(36),
  ENTREGA smallint DEFAULT 0,
  COMPROBANTEELECTRONICO smallint DEFAULT 1,
  ESPECIALIDAD varchar(12),
  NROHISTORIA bigint,
  MEDICO varchar(12),
  PPCONVENIO numeric(12,2),
  CONVENIO varchar(64),
  REFERENCIA varchar(512),
  DATAVALIDADA smallint DEFAULT 0,
  ESTADOPLE smallint DEFAULT 1,
  RESUMENID smallint,
  NROSORTEO integer,
  TASAICBPER numeric(12,2),
  CAT15_ELEM1 varchar(4),
  CAT15_ELEM2 varchar(4),
  CAT15_ELEM3 varchar(4),
  CAT15_ELEM4 varchar(4),
  CODDIRECCION varchar(4),
  CODLOCALANEXO varchar(4),
  PAGOEFECTIVO numeric(12,2),
  TIPOCLIENTE varchar(64),
  ORDENVENTA varchar(16),
  ENVIOWEBSERVICE smallint,
  TIPOOPERACION varchar(2) DEFAULT '01',
  TOTALANTICIPOS numeric(16,6),
  IDCRM integer,
  NROCUOTAS smallint,
  TELEFONO varchar(13),
  GARANTIA varchar(13),
  AUTORIZACION varchar(13),
  FECHACREACION date,
  TURNOCREACION smallint,
  NROCANJE integer,
  NUMPAGO varchar(32),
  CONSTRAINT INTEG_310 PRIMARY KEY (DUAL)
);
